### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by Study-gsl** [mhadnanali/FebAA#3]
Thank you for your wonderful work. I encountered a problem. When running multiple experiments for report, do we fix the random seed and run it again, or change the random seed and run it again? And for the results, taking bgrl+FebAA for example, is it the evaluation result from the pre training to the last round or the best evaluation result in the 10000 rounds? I look forward to your answers, thank you!

**Comment by mhadnanali** [comment]
Thank you for your nice words. 
If you will change the seeds you will get different results. If you want to run multiple times it depends on you what you are trying to achieve. (Same results or different results)

Training is on 10K epochs while for testing random 20 test sets are used. I hope the below line clarifies the confusion. 

flags.DEFINE_integer('num_eval_splits', 20, 'Number of different train/test splits the model will be evaluated over.')

if you will run [Get_Results.py](https://github.com/mhadnanali/FebAA/blob/main/BGRL%2BFebAA/Get_Results.py) file you will get results in csv file or you can see them in tensorboard.
